= Support
:awestruct-layout: project-standard
:awestruct-project: search

[[supported-versions]]
== Supported Products pass:[<i class="icon-user-md icon-fixed-width icon-2x"></i>]

Hibernate Search is a fully supported component of the https://www.redhat.com/en/products/runtimes[Red Hat Runtimes] offering.

Using JBoss EAP, Quarkus, Open Liberty or Spring Boot? They are all part of Red Hat Runtimes.

In addition, the https://www.redhat.com/en/technologies/jboss-middleware/data-grid[Red Hat Data Grid] provides optional extensions such as high performance real time replication for Hibernate Search powered applications running on one of the Red Hat supported runtime.

The Red Hat Data Grid also embeds a custom edition of Hibernate Search and allows using most of the same API to run high performance full-text queries and data mining on the data grid.

Several more products from Red Hat are powered by Hibernate Search.

If you are interested in Hibernate Search support/consulting within these runtimes, please https://www.redhat.com/en/contact[contact Red Hat]!
